import type { TemplateDefinition, TemplateDefaults } from "./template-registry.js";
import { templateRenderers } from "./templates.js";

// ── Shared font URLs ──
const FONTS = {
  satoshi: "https://api.fontshare.com/v2/css?f[]=satoshi@700,500,400&display=swap",
  cabinet: "https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@800,700,500&display=swap",
  general_sans: "https://api.fontshare.com/v2/css?f[]=general-sans@600,500,400&display=swap",
  clash_display: "https://api.fontshare.com/v2/css?f[]=clash-display@700,600,500&display=swap",
  switzer: "https://api.fontshare.com/v2/css?f[]=switzer@600,500,400&display=swap",
  zodiak: "https://api.fontshare.com/v2/css?f[]=zodiak@700,400&display=swap",
  dm_sans: "https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap",
  playfair: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;800&display=swap",
  space_grotesk: "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;700&display=swap",
  plus_jakarta: "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;800&display=swap",
  instrument_serif: "https://fonts.googleapis.com/css2?family=Instrument+Serif&display=swap",
  bebas: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
};

export const templatePresets: TemplateDefinition[] = [
  // ── 1. Aurora Gradient ──
  {
    id: "aurora-gradient",
    name: "Aurora Gradient",
    description: "Animated mesh gradient with floating orbs — vibrant and modern",
    category: ["general", "social", "entertainment", "travel"],
    tone: "bold",
    defaults: {
      background: {
        type: "gradient",
        colors: ["#6366F1", "#A855F7", "#EC4899"],
        angle: 135,
      },
      typography: {
        headline_font: "Cabinet Grotesk",
        headline_font_url: FONTS.cabinet,
        headline_weight: 800,
        headline_size_ratio: 0.042,
        headline_color: "#FFFFFF",
        headline_letter_spacing: "-0.02em",
        headline_line_height: 1.15,
        subheadline_font: "Satoshi",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.022,
        subheadline_color: "rgba(255,255,255,0.8)",
        subheadline_letter_spacing: "0",
      },
      device: {
        frame_style: "realistic",
        frame_color: "#1C1C1E",
        bezel_width: 8,
        corner_radius: 48,
        shadow: { enabled: true, color: "rgba(0,0,0,0.35)", blur: 60, spread: 0, offset_x: 0, offset_y: 25, layers: 2 },
        scale: 0.65,
        position: "center",
        reflection: false,
      },
      layout: {
        text_position: "top",
        text_alignment: "center",
        text_max_width: 85,
        padding: { top: 8, right: 6, bottom: 4, left: 6 },
        device_vertical_offset: 0,
        content_alignment: "center",
      },
      effects: {
        grain: { opacity: 0.04, size: 0.65 },
        blur_orbs: [
          { color: "#F472B6", size: 35, x: -5, y: 15, blur: 80, opacity: 0.35 },
          { color: "#818CF8", size: 30, x: 70, y: 65, blur: 70, opacity: 0.3 },
          { color: "#C084FC", size: 25, x: 30, y: 80, blur: 60, opacity: 0.25 },
        ],
      },
    },
    render: templateRenderers["aurora-gradient"],
  },

  // ── 2. Midnight Glass ──
  {
    id: "midnight-glass",
    name: "Midnight Glass",
    description: "Dark glassmorphism with subtle glow — premium fintech feel",
    category: ["finance", "productivity", "utility"],
    tone: "premium",
    defaults: {
      background: {
        type: "solid",
        colors: ["#6366F1", "#8B5CF6"],
      },
      typography: {
        headline_font: "Clash Display",
        headline_font_url: FONTS.clash_display,
        headline_weight: 600,
        headline_size_ratio: 0.038,
        headline_color: "#FFFFFF",
        headline_letter_spacing: "-0.01em",
        headline_line_height: 1.2,
        subheadline_font: "Switzer",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.02,
        subheadline_color: "rgba(255,255,255,0.55)",
        subheadline_letter_spacing: "0.02em",
      },
      device: {
        frame_style: "minimal",
        frame_color: "#2A2A2E",
        bezel_width: 0,
        corner_radius: 44,
        shadow: { enabled: true, color: "rgba(99,102,241,0.2)", blur: 80, spread: -10, offset_x: 0, offset_y: 20, layers: 3 },
        scale: 0.6,
        position: "center",
      },
      layout: {
        text_position: "top",
        text_alignment: "center",
        text_max_width: 80,
        padding: { top: 10, right: 6, bottom: 6, left: 6 },
        device_vertical_offset: 0,
        content_alignment: "center",
      },
      effects: {
        grain: { opacity: 0.06, size: 0.8 },
      },
    },
    render: templateRenderers["midnight-glass"],
  },

  // ── 3. Zen Minimal ──
  {
    id: "zen-minimal",
    name: "Zen Minimal",
    description: "Ultra-clean whitespace with refined typography",
    category: ["health", "productivity", "education", "utility"],
    tone: "minimal",
    defaults: {
      background: {
        type: "solid",
        colors: ["#FAFAF9"],
      },
      typography: {
        headline_font: "General Sans",
        headline_font_url: FONTS.general_sans,
        headline_weight: 600,
        headline_size_ratio: 0.035,
        headline_color: "#1A1A1A",
        headline_letter_spacing: "-0.02em",
        headline_line_height: 1.2,
        subheadline_font: "General Sans",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.02,
        subheadline_color: "#737373",
        subheadline_letter_spacing: "0",
      },
      device: {
        frame_style: "shadow-only",
        frame_color: "#E5E5E5",
        bezel_width: 0,
        corner_radius: 40,
        shadow: { enabled: true, color: "rgba(0,0,0,0.08)", blur: 40, spread: -5, offset_x: 0, offset_y: 15, layers: 1 },
        scale: 0.6,
        position: "center",
      },
      layout: {
        text_position: "top",
        text_alignment: "center",
        text_max_width: 75,
        padding: { top: 10, right: 8, bottom: 6, left: 8 },
        device_vertical_offset: 0,
        content_alignment: "center",
      },
      effects: {},
    },
    render: templateRenderers["zen-minimal"],
  },

  // ── 4. Bold Showcase ──
  {
    id: "bold-showcase",
    name: "Bold Showcase",
    description: "Giant typography with device peeking from bottom edge",
    category: ["ecommerce", "social", "entertainment", "general"],
    tone: "bold",
    defaults: {
      background: {
        type: "gradient",
        colors: ["#0F172A", "#1E293B"],
        angle: 160,
      },
      typography: {
        headline_font: "Cabinet Grotesk",
        headline_font_url: FONTS.cabinet,
        headline_weight: 800,
        headline_size_ratio: 0.058,
        headline_color: "#FFFFFF",
        headline_letter_spacing: "-0.03em",
        headline_line_height: 1.05,
        subheadline_font: "Satoshi",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.022,
        subheadline_color: "rgba(255,255,255,0.6)",
        subheadline_letter_spacing: "0.01em",
      },
      device: {
        frame_style: "realistic",
        frame_color: "#1C1C1E",
        bezel_width: 8,
        corner_radius: 48,
        shadow: { enabled: true, color: "rgba(0,0,0,0.5)", blur: 60, spread: 0, offset_x: 0, offset_y: 30, layers: 2 },
        scale: 0.7,
        position: "bottom",
      },
      layout: {
        text_position: "top",
        text_alignment: "left",
        text_max_width: 90,
        padding: { top: 8, right: 6, bottom: 0, left: 8 },
        device_vertical_offset: 5,
        content_alignment: "start",
      },
      effects: {
        grain: { opacity: 0.03, size: 0.7 },
      },
    },
    render: templateRenderers["bold-showcase"],
  },

  // ── 5. Candy Pop ──
  {
    id: "candy-pop",
    name: "Candy Pop",
    description: "Playful and colorful with dot patterns and badges",
    category: ["social", "entertainment", "food", "ecommerce"],
    tone: "playful",
    defaults: {
      background: {
        type: "solid",
        colors: ["#FEF3C7", "#F59E0B"],
      },
      typography: {
        headline_font: "Plus Jakarta Sans",
        headline_font_url: FONTS.plus_jakarta,
        headline_weight: 800,
        headline_size_ratio: 0.04,
        headline_color: "#1C1917",
        headline_letter_spacing: "-0.02em",
        headline_line_height: 1.2,
        subheadline_font: "Plus Jakarta Sans",
        subheadline_weight: 500,
        subheadline_size_ratio: 0.02,
        subheadline_color: "#78716C",
        subheadline_letter_spacing: "0",
      },
      device: {
        frame_style: "realistic",
        frame_color: "#1C1C1E",
        bezel_width: 7,
        corner_radius: 44,
        shadow: { enabled: true, color: "rgba(0,0,0,0.15)", blur: 40, spread: 0, offset_x: 0, offset_y: 20, layers: 1 },
        scale: 0.6,
        position: "center",
      },
      layout: {
        text_position: "top",
        text_alignment: "center",
        text_max_width: 85,
        padding: { top: 8, right: 6, bottom: 5, left: 6 },
        device_vertical_offset: 0,
        content_alignment: "center",
      },
      effects: {
        dots_pattern: { size: 2, gap: 24, color: "#D97706", opacity: 0.12 },
        blur_orbs: [
          { color: "#FDE68A", size: 40, x: -10, y: 70, blur: 80, opacity: 0.5 },
          { color: "#FBBF24", size: 30, x: 80, y: 10, blur: 60, opacity: 0.3 },
        ],
      },
    },
    render: templateRenderers["candy-pop"],
  },

  // ── 6. Noir Elegance ──
  {
    id: "noir-elegance",
    name: "Noir Elegance",
    description: "Pure black with gold accents and thin line patterns",
    category: ["finance", "productivity"],
    tone: "luxury",
    defaults: {
      background: {
        type: "solid",
        colors: ["#0A0A0A", "#D4AF37"],
      },
      typography: {
        headline_font: "Instrument Serif",
        headline_font_url: FONTS.instrument_serif,
        headline_weight: 400,
        headline_size_ratio: 0.042,
        headline_color: "#FFFFFF",
        headline_letter_spacing: "0",
        headline_line_height: 1.2,
        subheadline_font: "Switzer",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.018,
        subheadline_color: "rgba(255,255,255,0.4)",
        subheadline_letter_spacing: "0.08em",
        headline_text_transform: undefined,
      },
      device: {
        frame_style: "outline",
        frame_color: "rgba(212,175,55,0.3)",
        bezel_width: 0,
        corner_radius: 44,
        shadow: { enabled: true, color: "rgba(212,175,55,0.1)", blur: 60, spread: 0, offset_x: 0, offset_y: 20, layers: 2 },
        scale: 0.6,
        position: "center",
        reflection: true,
      },
      layout: {
        text_position: "top",
        text_alignment: "center",
        text_max_width: 80,
        padding: { top: 10, right: 6, bottom: 8, left: 6 },
        device_vertical_offset: 0,
        content_alignment: "center",
      },
      effects: {
        lines_pattern: { width: 0.5, gap: 40, color: "rgba(212,175,55,0.08)", opacity: 1, angle: -30 },
      },
    },
    render: templateRenderers["noir-elegance"],
  },

  // ── 7. Neon Glow ──
  {
    id: "neon-glow",
    name: "Neon Glow",
    description: "Cyberpunk-inspired with neon borders and grid background",
    category: ["entertainment", "social"],
    tone: "tech",
    defaults: {
      background: {
        type: "solid",
        colors: ["#0C0C14", "#22D3EE"],
      },
      typography: {
        headline_font: "Space Grotesk",
        headline_font_url: FONTS.space_grotesk,
        headline_weight: 700,
        headline_size_ratio: 0.04,
        headline_color: "#FFFFFF",
        headline_letter_spacing: "-0.01em",
        headline_line_height: 1.15,
        subheadline_font: "Space Grotesk",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.02,
        subheadline_color: "rgba(34,211,238,0.7)",
        subheadline_letter_spacing: "0.03em",
      },
      device: {
        frame_style: "minimal",
        frame_color: "#1C1C2E",
        bezel_width: 0,
        corner_radius: 44,
        shadow: { enabled: true, color: "rgba(34,211,238,0.15)", blur: 50, spread: 0, offset_x: 0, offset_y: 15, layers: 2 },
        scale: 0.6,
        position: "center",
      },
      layout: {
        text_position: "top",
        text_alignment: "center",
        text_max_width: 80,
        padding: { top: 9, right: 6, bottom: 6, left: 6 },
        device_vertical_offset: 0,
        content_alignment: "center",
      },
      effects: {},
    },
    render: templateRenderers["neon-glow"],
  },

  // ── 8. Frost Blur ──
  {
    id: "frost-blur",
    name: "Frost Blur",
    description: "Blurred screenshot as background with frosted glass overlay",
    category: ["general", "productivity", "finance", "utility"],
    tone: "premium",
    defaults: {
      background: { type: "blur", colors: [] },
      typography: {
        headline_font: "Satoshi",
        headline_font_url: FONTS.satoshi,
        headline_weight: 700,
        headline_size_ratio: 0.038,
        headline_color: "#FFFFFF",
        headline_letter_spacing: "-0.01em",
        headline_line_height: 1.2,
        subheadline_font: "Satoshi",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.02,
        subheadline_color: "rgba(255,255,255,0.75)",
        subheadline_letter_spacing: "0",
      },
      device: {
        frame_style: "realistic",
        frame_color: "#1C1C1E",
        bezel_width: 8,
        corner_radius: 48,
        shadow: { enabled: true, color: "rgba(0,0,0,0.3)", blur: 50, spread: 0, offset_x: 0, offset_y: 20, layers: 2 },
        scale: 0.62,
        position: "center",
      },
      layout: {
        text_position: "top",
        text_alignment: "center",
        text_max_width: 80,
        padding: { top: 9, right: 6, bottom: 5, left: 6 },
        device_vertical_offset: 0,
        content_alignment: "center",
      },
      effects: {
        grain: { opacity: 0.05, size: 0.7 },
      },
    },
    render: templateRenderers["frost-blur"],
  },

  // ── 9. Organic Wave ──
  {
    id: "organic-wave",
    name: "Organic Wave",
    description: "Flowing wave shapes with natural tones",
    category: ["health", "travel", "food"],
    tone: "organic",
    defaults: {
      background: {
        type: "solid",
        colors: ["#F0FDF4", "#22C55E"],
      },
      typography: {
        headline_font: "DM Sans",
        headline_font_url: FONTS.dm_sans,
        headline_weight: 700,
        headline_size_ratio: 0.038,
        headline_color: "#14532D",
        headline_letter_spacing: "-0.02em",
        headline_line_height: 1.2,
        subheadline_font: "DM Sans",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.02,
        subheadline_color: "#6B7280",
        subheadline_letter_spacing: "0",
      },
      device: {
        frame_style: "shadow-only",
        frame_color: "#D1D5DB",
        bezel_width: 0,
        corner_radius: 40,
        shadow: { enabled: true, color: "rgba(0,0,0,0.1)", blur: 40, spread: -5, offset_x: 0, offset_y: 15, layers: 1 },
        scale: 0.6,
        position: "center",
      },
      layout: {
        text_position: "top",
        text_alignment: "center",
        text_max_width: 80,
        padding: { top: 9, right: 6, bottom: 5, left: 6 },
        device_vertical_offset: 0,
        content_alignment: "center",
      },
      effects: {},
    },
    render: templateRenderers["organic-wave"],
  },

  // ── 10. Editorial Stack ──
  {
    id: "editorial-stack",
    name: "Editorial Stack",
    description: "Magazine layout with text on left, device on right",
    category: ["education", "productivity", "general"],
    tone: "editorial",
    defaults: {
      background: {
        type: "solid",
        colors: ["#FFFFFF", "#2563EB"],
      },
      typography: {
        headline_font: "Zodiak",
        headline_font_url: FONTS.zodiak,
        headline_weight: 700,
        headline_size_ratio: 0.04,
        headline_color: "#0F172A",
        headline_letter_spacing: "-0.02em",
        headline_line_height: 1.15,
        subheadline_font: "General Sans",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.018,
        subheadline_color: "#64748B",
        subheadline_letter_spacing: "0",
      },
      device: {
        frame_style: "realistic",
        frame_color: "#1C1C1E",
        bezel_width: 7,
        corner_radius: 44,
        shadow: { enabled: true, color: "rgba(0,0,0,0.12)", blur: 40, spread: 0, offset_x: 0, offset_y: 15, layers: 1 },
        scale: 0.55,
        position: "center",
      },
      layout: {
        text_position: "left",
        text_alignment: "left",
        text_max_width: 100,
        padding: { top: 8, right: 5, bottom: 8, left: 8 },
        device_vertical_offset: 0,
        content_alignment: "center",
      },
      effects: {},
    },
    render: templateRenderers["editorial-stack"],
  },

  // ── 11. Panoramic Hero ──
  {
    id: "panoramic-hero",
    name: "Panoramic Hero",
    description: "Full-bleed screenshot with gradient text overlay",
    category: ["travel", "entertainment", "social"],
    tone: "bold",
    defaults: {
      background: {
        type: "gradient",
        colors: ["rgba(0,0,0,0.85)", "rgba(0,0,0,0)"],
      },
      typography: {
        headline_font: "Bebas Neue",
        headline_font_url: FONTS.bebas,
        headline_weight: 400,
        headline_size_ratio: 0.065,
        headline_color: "#FFFFFF",
        headline_letter_spacing: "0.04em",
        headline_line_height: 1.0,
        headline_text_transform: "uppercase",
        subheadline_font: "Satoshi",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.022,
        subheadline_color: "rgba(255,255,255,0.7)",
        subheadline_letter_spacing: "0.02em",
      },
      device: {
        frame_style: "none",
        frame_color: "",
        bezel_width: 0,
        corner_radius: 0,
        shadow: { enabled: false, color: "", blur: 0, spread: 0, offset_x: 0, offset_y: 0 },
        scale: 1.0,
        position: "center",
      },
      layout: {
        text_position: "overlay",
        text_alignment: "left",
        text_max_width: 85,
        padding: { top: 0, right: 8, bottom: 8, left: 8 },
        device_vertical_offset: 0,
        content_alignment: "end",
      },
      effects: {},
    },
    render: templateRenderers["panoramic-hero"],
  },

  // ── 12. Duo Showcase ──
  {
    id: "duo-showcase",
    name: "Duo Showcase",
    description: "Two screenshots side by side with slight rotation",
    category: ["general", "social", "ecommerce"],
    tone: "bold",
    defaults: {
      background: {
        type: "gradient",
        colors: ["#1E1B4B", "#4338CA", "#7C3AED"],
        angle: 135,
      },
      typography: {
        headline_font: "Cabinet Grotesk",
        headline_font_url: FONTS.cabinet,
        headline_weight: 700,
        headline_size_ratio: 0.038,
        headline_color: "#FFFFFF",
        headline_letter_spacing: "-0.01em",
        headline_line_height: 1.2,
        subheadline_font: "Satoshi",
        subheadline_weight: 400,
        subheadline_size_ratio: 0.02,
        subheadline_color: "rgba(255,255,255,0.7)",
        subheadline_letter_spacing: "0",
      },
      device: {
        frame_style: "realistic",
        frame_color: "#1C1C1E",
        bezel_width: 7,
        corner_radius: 44,
        shadow: { enabled: true, color: "rgba(0,0,0,0.3)", blur: 40, spread: 0, offset_x: 0, offset_y: 15, layers: 1 },
        scale: 0.45,
        position: "center",
      },
      layout: {
        text_position: "top",
        text_alignment: "center",
        text_max_width: 85,
        padding: { top: 7, right: 5, bottom: 4, left: 5 },
        device_vertical_offset: 0,
        content_alignment: "center",
      },
      effects: {
        grain: { opacity: 0.04, size: 0.65 },
      },
    },
    render: templateRenderers["duo-showcase"],
  },
];

// Lookup map
export const presetMap = new Map(
  templatePresets.map((t) => [t.id, t])
);

// Legacy aliases
presetMap.set("clean-gradient", presetMap.get("aurora-gradient")!);
presetMap.set("dark-premium", presetMap.get("midnight-glass")!);
presetMap.set("minimal-flat", presetMap.get("zen-minimal")!);
presetMap.set("bold-feature", presetMap.get("bold-showcase")!);
presetMap.set("side-by-side", presetMap.get("duo-showcase")!);
